package mrr_javase_lab02;

public class Lab02Frame extends javax.swing.JFrame {

    /**
     * Creates new form Lab02Frame
     */
    public Lab02Frame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ResolveButton = new javax.swing.JButton();
        ExitButton = new javax.swing.JButton();
        ClearButton = new javax.swing.JButton();
        XVariableLabel = new javax.swing.JTextField();
        BVariableLabel = new javax.swing.JTextField();
        CVariableLabel = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        AVariableLabel = new javax.swing.JTextField();
        ResultLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setMinimumSize(new java.awt.Dimension(800, 600));
        getContentPane().setLayout(null);

        ResolveButton.setText("РЕШИТЬ");
        ResolveButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ResolveButtonActionPerformed(evt);
            }
        });
        getContentPane().add(ResolveButton);
        ResolveButton.setBounds(160, 220, 101, 23);

        ExitButton.setText("ВЫХОД");
        ExitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExitButtonActionPerformed(evt);
            }
        });
        getContentPane().add(ExitButton);
        ExitButton.setBounds(390, 260, 69, 23);

        ClearButton.setText("ОЧИСТИТЬ");
        ClearButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ClearButtonActionPerformed(evt);
            }
        });
        getContentPane().add(ClearButton);
        ClearButton.setBounds(313, 220, 110, 23);

        XVariableLabel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                XVariableLabelActionPerformed(evt);
            }
        });
        getContentPane().add(XVariableLabel);
        XVariableLabel.setBounds(48, 38, 70, 20);
        getContentPane().add(BVariableLabel);
        BVariableLabel.setBounds(48, 76, 70, 20);
        getContentPane().add(CVariableLabel);
        CVariableLabel.setBounds(48, 114, 70, 20);

        jLabel1.setText("X");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(24, 41, 20, 14);

        jLabel2.setText("B");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(24, 79, 20, 14);

        jLabel3.setText("C");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(24, 117, 20, 14);

        jLabel4.setBackground(new java.awt.Color(255, 255, 255));
        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mrr_javase_lab02/IconForLabel.png"))); // NOI18N
        jLabel4.setOpaque(true);
        getContentPane().add(jLabel4);
        jLabel4.setBounds(125, 41, 329, 93);

        jLabel5.setText("A");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(20, 150, 30, 14);
        getContentPane().add(AVariableLabel);
        AVariableLabel.setBounds(50, 150, 70, 20);

        ResultLabel.setBackground(new java.awt.Color(255, 255, 255));
        ResultLabel.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        ResultLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ResultLabel.setText("РЕЗУЛЬТАТ");
        ResultLabel.setOpaque(true);
        getContentPane().add(ResultLabel);
        ResultLabel.setBounds(160, 150, 260, 60);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void XVariableLabelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_XVariableLabelActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_XVariableLabelActionPerformed

    private void ResolveButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ResolveButtonActionPerformed
        // TODO add your handling code here:
        String LabelResult = new String();
        ResultLabel.setText(ResolveFunction(LabelResult));
    }//GEN-LAST:event_ResolveButtonActionPerformed

    private void ClearButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ClearButtonActionPerformed
        ResultLabel.setText("Do again");
    }//GEN-LAST:event_ClearButtonActionPerformed

    private void ExitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExitButtonActionPerformed
      dispose();
    }//GEN-LAST:event_ExitButtonActionPerformed
    
    

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Lab02Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Lab02Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Lab02Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Lab02Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Lab02Frame().setVisible(true);
            }
        });
    }
    
    public String ResolveFunction(String y){
        try{
                int x = Integer.parseInt(XVariableLabel.getText());
                int b = Integer.parseInt(BVariableLabel.getText());
                int c = Integer.parseInt(CVariableLabel.getText());
                int a = Integer.parseInt(AVariableLabel.getText());
                int temp; 
                try{
                    if(x<4){
                    temp = (int) ((Math.pow(x,2)+Math.pow(a, 2))*c)/2*b;
                    y = String.valueOf(temp);
                    
                }
                    if(x>=4){
                    temp = (int) (Math.pow(x,3)*(a-b));
                    y = String.valueOf(temp);
                }
                    }
        catch(NullPointerException e){
                    y = "NaN Excep";
                    }    
            }
        catch(Exception e){
            y = "Try again, u do something wrong";
            }
        
       return y;
    }
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField AVariableLabel;
    private javax.swing.JTextField BVariableLabel;
    private javax.swing.JTextField CVariableLabel;
    private javax.swing.JButton ClearButton;
    private javax.swing.JButton ExitButton;
    private javax.swing.JButton ResolveButton;
    private javax.swing.JLabel ResultLabel;
    private javax.swing.JTextField XVariableLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    // End of variables declaration//GEN-END:variables
}

